[build]
builder = "Nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = ". /opt/venv/bin/activate && PYTHONPATH=/app uvicorn src.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
