services:
  - type: web
    name: meeting-summarizer-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: UPLOAD_DIR
        value: /tmp/audio_uploads
      - key: CHUNK_SIZE
        value: 4000
      - key: CHUNK_OVERLAP
        value: 200
      - key: GROQ_MODEL_NAME
        value: llama-3.3-70b-versatile
      - key: API_V1_STR
        value: /api/v1
      - key: GROQ_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
  - type: web
    name: meeting-summarizer-frontend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.headless true --server.address 0.0.0.0
    envVars:
      - key: FASTAPI_BASE_URL
        value: https://meeting-summarizer-backend.onrender.com
      - key: GROQ_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
